### ISSUE TITLE
Second definition of lsp-treemacs--symbol-icon

### ISSUE THREAD

**Issue by algoterranean** [emacs-lsp/lsp-treemacs#26] opened 2019-12-06 16:57 UTC
Did you mean to redefine `lsp-treemacs--symbol-icon` in `lsp-treemacs.el`? 

The second `defun` does not display icons for me, but the first one works fine (at least, it displays the icons properly, but indentation seems to be lacking for child nodes... not sure if this is related).

**Comment by yyoncho** [comment] 2019-12-06 17:23
Can you post a screenshot about the identation issues?

**Comment by yyoncho** [comment] 2019-12-06 17:25
I pushed a fix about the duplicate name.

**Comment by algoterranean** [comment] 2019-12-06 17:37
Using this Python code:

```
import os
import sys

class Example:
    def __init__(self):
        self.x = 1
```
I would expect lsp-treemacs-symbols-list to display the symbols like, say:

```
os
sys
Example
     __init__
        x
```

What I get is (with your 2nd defun):

![image](https://user-images.githubusercontent.com/6758520/70342927-a3d43b00-181b-11ea-8219-16402f00416d.png)

What I get (with the 1st defun):

![image](https://user-images.githubusercontent.com/6758520/70342984-c6665400-181b-11ea-80a3-ac914bb749b9.png)

It looks like `(seq-empty-p children)` is always true.

FWIW, evaluating 
```
(lsp-request "textDocument/documentSymbol" `(:textDocument ,(lsp--text-document-identifier)))
```
in my code buffer gives me:

`(#s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (name os containerName nil location #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (uri file:///mnt/projects/t.py range #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (start #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (line 0 character 0)) end #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (line 0 character 9)))))) kind 2)) #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (name sys containerName nil location #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (uri file:///mnt/projects/t.py range #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (start #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (line 1 character 0)) end #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (line 1 character 10)))))) kind 2)) #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (name Example containerName nil location #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (uri file:///mnt/projects/t.py range #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (start #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (line 3 character 0)) end #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (line 6 character 0)))))) kind 5)) #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (name __init__ containerName Example location #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (uri file:///mnt/projects/t.py range #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (start #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (line 4 character 4)) end #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (line 6 character 0)))))) kind 12)) #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (name x containerName __init__ location #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (uri file:///mnt/projects/t.py range #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (start #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (line 5 character 8)) end #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (line 5 character 18)))))) kind 13)))`

Not sure if `children` is supposed to be included in this return value, but it does include a `containerName` reference.

I am using Palantir's python language server for this (https://github.com/palantir/python-language-server) not the MS one, if that makes a difference.

**Comment by yyoncho** [comment] 2019-12-06 17:45
Ah, I see - the offset is the expected behaviour here it is the explanation:

![Screenshot](https://user-images.githubusercontent.com/13259670/70343671-89708080-1860-11ea-8b6b-69757d355153.png)

Note that in order to have the nodes without children aligned to the nodes with children aligned we have to indent then in the same way.

VScode works in the same way: 
![Screenshot](https://user-images.githubusercontent.com/13259670/70343825-e79d6380-1860-11ea-9677-d948098f12bc.png)

**Comment by algoterranean** [comment] 2019-12-06 17:48
Shouldn't the expected behavior though be to have, for example, `__init__` indented as a child of `Example`, since it is a method?

**Comment by yyoncho** [comment] 2019-12-06 17:49
Yes, please ignore the previous comment, apparently, there is pyls specific an issue. I will investigate.

**Comment by algoterranean** [comment] 2019-12-06 18:08
Using the MS python language server seems to fix the indentation issue:

![image](https://user-images.githubusercontent.com/6758520/70344983-8e154480-1820-11ea-9c24-000b6a638f3a.png)

And this backend does return a `children `node:

`(#s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (name os kind 2 deprecated nil range #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (start #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (line 0 character 7)) end #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (line 0 character 9)))) selectionRange #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (start #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (line 0 character 7)) end #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (line 0 character 9)))) children [])) #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (name sys kind 2 deprecated nil range #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (start #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (line 1 character 7)) end #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (line 1 character 10)))) selectionRange #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (start #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (line 1 character 7)) end #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (line 1 character 10)))) children [])) #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (name Example kind 5 deprecated nil range #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (start #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (line 3 character 0)) end #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (line 5 character 18)))) selectionRange #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (start #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (line 3 character 6)) end #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (line 3 character 13)))) children [#s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (name __init__ kind 9 deprecated nil range #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (start #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (line 4 character 4)) end #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (line 5 character 18)))) selectionRange #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (start #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (line 4 character 8)) end #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (line 4 character 16)))) children [#s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (name self kind 13 deprecated nil range #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (start #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (line 4 character 17)) end #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (line 4 character 21)))) selectionRange #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (start #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (line 4 character 17)) end #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (line 4 character 21)))) children []))]))])))`

Note though that `self.x` doesn't show up in the symbols list, but it's also not being returned from the backend as far as I can tell. So maybe I need to fool around with the config options for this LSP server.

**Comment by yyoncho** [comment] 2019-12-06 18:13
No, it is an issue in lsp-treemacs-symbols , I will fix it. It is caused by pyls not returning hierarchical elements. This was the old documentSymbols format.

**Comment by yyoncho** [comment] 2019-12-07 09:23
Proposed fix at https://github.com/emacs-lsp/lsp-treemacs/pull/27 

I will test it for some time before before merging.

**Comment by algoterranean** [comment] 2019-12-08 14:05
Thanks. The patch is working well for me so far!

**Comment by algoterranean** [comment] 2019-12-08 21:20
Actually, I noticed the symbols list is being truncated after the first class or defun. For example:

```
def test():
    x = 20
    
class Something:
    def __init__(self):
        x = 20
        
    def what(self):
        y = 90
```

Shows
![image](https://user-images.githubusercontent.com/6758520/70396381-20a71680-19ce-11ea-81fe-9ab75750c32a.png)


and 
```
class Something:
    def __init__(self):
        x = 20
        
    def what(self):
        y = 90


def test():
    x = 20 
```

Shows
![image](https://user-images.githubusercontent.com/6758520/70396388-39173100-19ce-11ea-943b-2919a6f0d09c.png)

Note that there looks to be a partial problem with indentation.

**Comment by yyoncho** [comment] 2019-12-09 20:12
@algoterranean pushed a fix, I was using the wrong function -split-with instead of -separate.

**Closed** 2019-12-10 16:06 UTC
